<a href="https://colab.research.google.com/github/Gowr93/DNN-NLP-Practise-Session-/blob/main/NLP_Grams_and_TF_IDF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd


In [ ]:
df = pd.DataFrame({'Text': ['This Pasta is Tasty', 'This Pasta is not Tasty'], 'Output:': [1,0]})

In [ ]:
df

Text  Output:
0      This Pasta is Tasty        1
1  This Pasta is not Tasty        0

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range = (1,1))

# ngram_range=(1,1)
# uni-gram or bow
# both are same here because ngram_range is 1,1

In [ ]:
# vocab
bow_uni_gram = cv.fit_transform(df['Text'])
print(cv.vocabulary_)

{'this': 4, 'pasta': 2, 'is': 0, 'tasty': 3, 'not': 1}


In [ ]:
cv1 = CountVectorizer(ngram_range = (1,2))
#Vocab
bow_uni_gram = cv1.fit_transform(df['Text'])
print(cv1.vocabulary_)
# this adds up to again and it added


{'this': 8, 'pasta': 5, 'is': 0, 'tasty': 7, 'this pasta': 9, 'pasta is': 6, 'is tasty': 2, 'not': 3, 'is not': 1, 'not tasty': 4}


In [ ]:
dataset = pd.DataFrame({'Text':['This Pasta is Tasty', 'This Pasta is not Tasty',
                          'Pasty is delecious','I like pasta very much',
                           'Pasta is good but cost is little high','Pasta tast is good and affordable',
                           'Pasta test is really nice however price is not an affordable'],
                   'Output':[1,0,1,1,0,1,0]})

In [ ]:
dataset

Text  Output
0                                This Pasta is Tasty       1
1                            This Pasta is not Tasty       0
2                                 Pasty is delecious       1
3                             I like pasta very much       1
4              Pasta is good but cost is little high       0
5                  Pasta tast is good and affordable       1
6  Pasta test is really nice however price is not...       0

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(1,1))

In [ ]:
bow_uni_gram = cv.fit_transform(dataset['Text'])
print(cv.vocabulary_)

{'this': 22, 'pasta': 15, 'is': 9, 'tasty': 20, 'not': 14, 'pasty': 16, 'delecious': 5, 'like': 10, 'very': 23, 'much': 12, 'good': 6, 'but': 3, 'cost': 4, 'little': 11, 'high': 7, 'tast': 19, 'and': 2, 'affordable': 0, 'test': 21, 'really': 18, 'nice': 13, 'however': 8, 'price': 17, 'an': 1}


In [ ]:
cv3 = CountVectorizer(ngram_range=(3,3))
bow_tri_gram = cv3.fit_transform(dataset['Text'])
print(cv3.vocabulary_)

{'this pasta is': 25, 'pasta is tasty': 16, 'pasta is not': 15, 'is not tasty': 9, 'pasty is delecious': 20, 'like pasta very': 11, 'pasta very much': 19, 'pasta is good': 14, 'is good but': 6, 'good but cost': 3, 'but cost is': 0, 'cost is little': 1, 'is little high': 7, 'pasta tast is': 17, 'tast is good': 23, 'is good and': 5, 'good and affordable': 2, 'pasta test is': 18, 'test is really': 24, 'is really nice': 10, 'really nice however': 22, 'nice however price': 12, 'however price is': 4, 'price is not': 21, 'is not an': 8, 'not an affordable': 13}


In [ ]:
print(bow_tri_gram.toarray())

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [1 1 0 1 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0]
 [0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 0 0 0 1 0 0 1 1 0 1 0]]


In [ ]:
# N-Grams
### 1) Sparsity , not diff significant words, OOV


In [ ]:
dataset

Text  Output
0                                This Pasta is Tasty       1
1                            This Pasta is not Tasty       0
2                                 Pasty is delecious       1
3                             I like pasta very much       1
4              Pasta is good but cost is little high       0
5                  Pasta tast is good and affordable       1
6  Pasta test is really nice however price is not...       0

## Term Frequency - Inverse Documents
##Frequency

In [ ]:
from sklearn.feature_extraction.text import TfidVectorizer
tfidf = TfidVectorizer()
tfidf.fit_transform(dataset['Text']).toarray()


ImportError: cannot import name 'TfidVectorizer' from 'sklearn.feature_extraction.text' (/usr/local/lib/python3.11/dist-packages/sklearn/feature_extraction/text.py)

## New Project Spacy

In [ ]:
!pip install spacy

In [2]:
#!python -m spacy download en_core_web_sm

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 129.6 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.


In [3]:
import spacy

In [4]:
nlp = spacy.load('en_core_web_sm')

In [5]:
doc = nlp("Five Indian Army personnel were killed on July 8 after terrorists ambushed an Army convoy in Badnota village, which is 124 km from Kathua town in Jammu. The attack also came on the death anniversary of Hizbul Mujahideen operative Burhan Wani, who was killed in an encounter on July 8, 2016, in south Kashmir. This is the fourth terror-incident in the State within 48 hours and the latest in a series of attacks in the last few months, especially in the Jammu region, reinforcing a new trend of terrorism in Jammu and Kashmir shifting towards the Rajouri-Poonch area. On June 9, terrorists attacked a bus in Reasi district killing nine pilgrims and leaving 33 injured, the day Prime Minister Narendra Modi was being sworn in for a third term in office. This attack on the pilgrims was a new low. This region has been quiet for over two decades now, after being a hotbed of insurgency in the late 1990s and early 2000s. This was brought under control by Operation Sarp Vinash in 2003 and subsequent support from the locals, especially the Gujjar-Bakerwal community.Recurring incidents of security forces being ambushed have resulted in casualties, which is unacceptable for a highly trained and professional force like the Indian Army. This calls for stricter adherence to standard operating procedures and improved operations. While the ceasefire along the Line of Control (LoC) largely holds, the uptick in terror incidents is a matter of concern — more so, the shift in violence. There are many factors that may be leading to this trend. A major one is the vacuum on the ground with a large number of troops redeployed to the Line of Actual Control in Eastern Ladakh in the aftermath of the 2020 standoff with China. This has resulted in a gap in local intelligence. There is also the increased use of modern but easily available technology by terrorist groups looking to find new routes to keep the insurgency going. Botched-up security operations have also damaged the trust between the local population and the state. From foreign terrorists crossing the LoC and leading the attacks, there has been a trend now to push local militants to the forefront to give the insurgency a more home-grown face as international pressure has mounted on Pakistan. New terror groups have also come up claiming to be behind some of the attacks. These aspects present new challenges. Tackling the situation needs a multi-layered strategy beyond just augmenting troop levels. Quick and decisive action at the highest levels of the government, bringing in all stakeholders, is the need of the hour.")

In [6]:
doc


Five Indian Army personnel were killed on July 8 after terrorists ambushed an Army convoy in Badnota village, which is 124 km from Kathua town in Jammu. The attack also came on the death anniversary of Hizbul Mujahideen operative Burhan Wani, who was killed in an encounter on July 8, 2016, in south Kashmir. This is the fourth terror-incident in the State within 48 hours and the latest in a series of attacks in the last few months, especially in the Jammu region, reinforcing a new trend of terrorism in Jammu and Kashmir shifting towards the Rajouri-Poonch area. On June 9, terrorists attacked a bus in Reasi district killing nine pilgrims and leaving 33 injured, the day Prime Minister Narendra Modi was being sworn in for a third term in office. This attack on the pilgrims was a new low. This region has been quiet for over two decades now, after being a hotbed of insurgency in the late 1990s and early 2000s. This was brought under control by Operation Sarp Vinash in 2003 and subsequent sup

In [7]:
# Tokenize a Document
for token in doc:
  print(token.text, token.pos_, token.dep_)

Five NUM nummod
Indian ADJ amod
Army PROPN compound
personnel NOUN nsubjpass
were AUX auxpass
killed VERB ROOT
on ADP prep
July PROPN pobj
8 NUM nummod
after SCONJ mark
terrorists NOUN nsubj
ambushed VERB advcl
an DET det
Army PROPN compound
convoy NOUN dobj
in ADP prep
Badnota PROPN compound
village NOUN pobj
, PUNCT punct
which PRON nsubj
is AUX relcl
124 NUM nummod
km NOUN attr
from ADP prep
Kathua PROPN compound
town NOUN pobj
in ADP prep
Jammu PROPN pobj
. PUNCT punct
The DET det
attack NOUN nsubj
also ADV advmod
came VERB ROOT
on ADP prep
the DET det
death NOUN compound
anniversary NOUN pobj
of ADP prep
Hizbul PROPN compound
Mujahideen PROPN compound
operative NOUN compound
Burhan PROPN compound
Wani PROPN pobj
, PUNCT punct
who PRON nsubjpass
was AUX auxpass
killed VERB relcl
in ADP prep
an DET det
encounter NOUN pobj
on ADP prep
July PROPN pobj
8 NUM nummod
, PUNCT punct
2016 NUM nummod
, PUNCT punct
in ADP prep
south ADJ amod
Kashmir PROPN pobj
. PUNCT punct
This PRON nsubj
is

In [8]:
for token in doc:
  print(token.text)

Five
Indian
Army
personnel
were
killed
on
July
8
after
terrorists
ambushed
an
Army
convoy
in
Badnota
village
,
which
is
124
km
from
Kathua
town
in
Jammu
.
The
attack
also
came
on
the
death
anniversary
of
Hizbul
Mujahideen
operative
Burhan
Wani
,
who
was
killed
in
an
encounter
on
July
8
,
2016
,
in
south
Kashmir
.
This
is
the
fourth
terror
-
incident
in
the
State
within
48
hours
and
the
latest
in
a
series
of
attacks
in
the
last
few
months
,
especially
in
the
Jammu
region
,
reinforcing
a
new
trend
of
terrorism
in
Jammu
and
Kashmir
shifting
towards
the
Rajouri
-
Poonch
area
.
On
June
9
,
terrorists
attacked
a
bus
in
Reasi
district
killing
nine
pilgrims
and
leaving
33
injured
,
the
day
Prime
Minister
Narendra
Modi
was
being
sworn
in
for
a
third
term
in
office
.
This
attack
on
the
pilgrims
was
a
new
low
.
This
region
has
been
quiet
for
over
two
decades
now
,
after
being
a
hotbed
of
insurgency
in
the
late
1990s
and
early
2000s
.
This
was
brought
under
control
by
Operation
Sarp
Vinash
in
2003

In [9]:
for token in doc:
  print(f"{token.text}:{token.pos_}")

Five:NUM
Indian:ADJ
Army:PROPN
personnel:NOUN
were:AUX
killed:VERB
on:ADP
July:PROPN
8:NUM
after:SCONJ
terrorists:NOUN
ambushed:VERB
an:DET
Army:PROPN
convoy:NOUN
in:ADP
Badnota:PROPN
village:NOUN
,:PUNCT
which:PRON
is:AUX
124:NUM
km:NOUN
from:ADP
Kathua:PROPN
town:NOUN
in:ADP
Jammu:PROPN
.:PUNCT
The:DET
attack:NOUN
also:ADV
came:VERB
on:ADP
the:DET
death:NOUN
anniversary:NOUN
of:ADP
Hizbul:PROPN
Mujahideen:PROPN
operative:NOUN
Burhan:PROPN
Wani:PROPN
,:PUNCT
who:PRON
was:AUX
killed:VERB
in:ADP
an:DET
encounter:NOUN
on:ADP
July:PROPN
8:NUM
,:PUNCT
2016:NUM
,:PUNCT
in:ADP
south:ADJ
Kashmir:PROPN
.:PUNCT
This:PRON
is:AUX
the:DET
fourth:ADJ
terror:NOUN
-:PUNCT
incident:NOUN
in:ADP
the:DET
State:PROPN
within:ADP
48:NUM
hours:NOUN
and:CCONJ
the:DET
latest:ADJ
in:ADP
a:DET
series:NOUN
of:ADP
attacks:NOUN
in:ADP
the:DET
last:ADJ
few:ADJ
months:NOUN
,:PUNCT
especially:ADV
in:ADP
the:DET
Jammu:PROPN
region:NOUN
,:PUNCT
reinforcing:VERB
a:DET
new:ADJ
trend:NOUN
of:ADP
terrorism:NOUN
in:ADP
Jammu

In [10]:
# Name Entity Recognition(NER)
for ner in doc.ents:
  print(f"{ner.text}:{ner.label_}")

Five:CARDINAL
Indian Army:ORG
July 8:DATE
Army:ORG
Badnota:GPE
124 km:QUANTITY
Kathua:ORG
Jammu:GPE
Hizbul Mujahideen:ORG
Burhan Wani:PERSON
July 8, 2016:DATE
Kashmir:LOC
fourth:ORDINAL
State:ORG
48 hours:TIME
the last few months:DATE
Jammu:GPE
Jammu:GPE
Kashmir:LOC
Rajouri:GPE
June 9:DATE
Reasi:GPE
nine:CARDINAL
33:CARDINAL
the day:DATE
Narendra Modi:PERSON
third:ORDINAL
over two decades:DATE
the late 1990s:DATE
early 2000s:DATE
Operation Sarp Vinash:ORG
2003:DATE
Gujjar:GPE
the Indian Army:ORG
the Line of Control (LoC:FAC
the Line of Actual Control:FAC
Eastern Ladakh:LOC
2020:DATE
China:GPE
LoC:ORG
Pakistan:GPE
the hour:TIME


In [11]:
for token in doc:
  print(f"{token.text}:{token.pos_}:{token.lemma_}")

Five:NUM:five
Indian:ADJ:indian
Army:PROPN:Army
personnel:NOUN:personnel
were:AUX:be
killed:VERB:kill
on:ADP:on
July:PROPN:July
8:NUM:8
after:SCONJ:after
terrorists:NOUN:terrorist
ambushed:VERB:ambush
an:DET:an
Army:PROPN:Army
convoy:NOUN:convoy
in:ADP:in
Badnota:PROPN:Badnota
village:NOUN:village
,:PUNCT:,
which:PRON:which
is:AUX:be
124:NUM:124
km:NOUN:km
from:ADP:from
Kathua:PROPN:Kathua
town:NOUN:town
in:ADP:in
Jammu:PROPN:Jammu
.:PUNCT:.
The:DET:the
attack:NOUN:attack
also:ADV:also
came:VERB:come
on:ADP:on
the:DET:the
death:NOUN:death
anniversary:NOUN:anniversary
of:ADP:of
Hizbul:PROPN:Hizbul
Mujahideen:PROPN:Mujahideen
operative:NOUN:operative
Burhan:PROPN:Burhan
Wani:PROPN:Wani
,:PUNCT:,
who:PRON:who
was:AUX:be
killed:VERB:kill
in:ADP:in
an:DET:an
encounter:NOUN:encounter
on:ADP:on
July:PROPN:July
8:NUM:8
,:PUNCT:,
2016:NUM:2016
,:PUNCT:,
in:ADP:in
south:ADJ:south
Kashmir:PROPN:Kashmir
.:PUNCT:.
This:PRON:this
is:AUX:be
the:DET:the
fourth:ADJ:fourth
terror:NOUN:terror
-:PUNCT:-
i

In [12]:
#Visualize

In [13]:
from IPython.core.display import display, HTML
from spacy import displacy

In [14]:
html = displacy.render(doc)
display(HTML(html))

<IPython.core.display.HTML object>

In [15]:
html = displacy.render(doc,style = 'ent')
display(HTML(html))

<IPython.core.display.HTML object>

## Stop Words

In [16]:
all_stopwords = nlp.Defaults.stop_words
print('\n List of all Stop-Words')
print(all_stopwords)


 List of all Stop-Words
{'almost', 'seeming', 'though', 'upon', 'hereupon', 'is', 'nothing', 'across', 'call', 'thereby', 'whereby', 'none', 'us', 'towards', 'we', 'hereby', '’m', 'next', "'re", 'except', '‘ve', 'she', 'your', 'still', 'mostly', "n't", 'herein', 'himself', 'fifteen', 'more', 'above', 'our', 'may', "'m", 'five', 'two', 'with', 'last', 'during', 'thereupon', 'me', 'where', 'they', 'thence', 'by', 'her', 'n‘t', 'seems', 'various', 'whose', 'did', 'twelve', 'one', 'per', 'their', 'sometime', 'must', 'anything', 'formerly', 'does', 'n’t', 'can', 'fifty', 'always', 'hers', 'anyone', 'be', 'name', 'you', 'had', 'anyhow', 'move', 'am', 'beyond', 'others', 'back', 'cannot', 'are', 'down', 'those', 'perhaps', 'whoever', 'also', 'show', 'own', 'thru', 'nor', 'eleven', 'at', 'through', 'what', 'whatever', 'noone', 'keep', 'something', 'which', 'latter', 'how', 'before', 'or', 'besides', 'were', 'beforehand', 'who', 'quite', 'within', 'why', 'whether', 'same', 'themselves', 'them'

In [17]:
text_tokens = []
for token in doc:
  text_tokens.append(token.text)


token_without_sw = [word for word in text_tokens if not word in all_stopwords]
print(token_without_sw)

['Five', 'Indian', 'Army', 'personnel', 'killed', 'July', '8', 'terrorists', 'ambushed', 'Army', 'convoy', 'Badnota', 'village', ',', '124', 'km', 'Kathua', 'town', 'Jammu', '.', 'The', 'attack', 'came', 'death', 'anniversary', 'Hizbul', 'Mujahideen', 'operative', 'Burhan', 'Wani', ',', 'killed', 'encounter', 'July', '8', ',', '2016', ',', 'south', 'Kashmir', '.', 'This', 'fourth', 'terror', '-', 'incident', 'State', '48', 'hours', 'latest', 'series', 'attacks', 'months', ',', 'especially', 'Jammu', 'region', ',', 'reinforcing', 'new', 'trend', 'terrorism', 'Jammu', 'Kashmir', 'shifting', 'Rajouri', '-', 'Poonch', 'area', '.', 'On', 'June', '9', ',', 'terrorists', 'attacked', 'bus', 'Reasi', 'district', 'killing', 'pilgrims', 'leaving', '33', 'injured', ',', 'day', 'Prime', 'Minister', 'Narendra', 'Modi', 'sworn', 'term', 'office', '.', 'This', 'attack', 'pilgrims', 'new', 'low', '.', 'This', 'region', 'quiet', 'decades', ',', 'hotbed', 'insurgency', 'late', '1990s', 'early', '2000s', 

## Mini_Project

In [18]:
! pip install vaderSentiment

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.0/126.0 kB 4.7 MB/s eta 0:00:00


In [19]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

In [20]:
analyser = SentimentIntensityAnalyzer()

In [23]:
def sentiment_analyzer(text):
  doc = nlp(text)
  sentiment = analyser.polarity_scores(text)
  sentiment_score = sentiment['compound']
  if sentiment_score >= 0.05:
    sentiment_label = 'Positive'
  elif sentiment_score <=-0.20:
    sentiment_label = 'Negative'
  else:
    sentiment_label = 'Neutral'

  return{'text': text, 'token':[token.text for token in doc], 'sentiment_score':sentiment_score, 'sentiment_label':sentiment_label}

In [27]:
texts = [
    "NLP is one of the hot topic now a days",
    'There are lots of demand in market about Sentliment analysis',
    "I'm not sure how I feel about the NLP",
    "I like this product very much",
    "I don't like this product at all",
    "This is worst experience I've ever had",
    "NLP is very elegant topic",
    "This is amazing experience",
    "One of the pathetic product",
    "My work desk is an organised mess."
]

In [28]:
for text in texts:
  result = sentiment_analyzer(text)
  print(result)

{'text': 'NLP is one of the hot topic now a days', 'token': ['NLP', 'is', 'one', 'of', 'the', 'hot', 'topic', 'now', 'a', 'days'], 'sentiment_score': 0.0, 'sentiment_label': 'Neutral'}
{'text': 'There are lots of demand in market about Sentliment analysis', 'token': ['There', 'are', 'lots', 'of', 'demand', 'in', 'market', 'about', 'Sentliment', 'analysis'], 'sentiment_score': -0.128, 'sentiment_label': 'Neutral'}
{'text': "I'm not sure how I feel about the NLP", 'token': ['I', "'m", 'not', 'sure', 'how', 'I', 'feel', 'about', 'the', 'NLP'], 'sentiment_score': -0.2411, 'sentiment_label': 'Negative'}
{'text': 'I like this product very much', 'token': ['I', 'like', 'this', 'product', 'very', 'much'], 'sentiment_score': 0.3612, 'sentiment_label': 'Positive'}
{'text': "I don't like this product at all", 'token': ['I', 'do', "n't", 'like', 'this', 'product', 'at', 'all'], 'sentiment_score': -0.2755, 'sentiment_label': 'Negative'}
{'text': "This is worst experience I've ever had", 'token': ['