<a href="https://colab.research.google.com/github/Gowr93/DNN-NLP-Practise-Session-/blob/main/Perceptron_Regression_problem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
## case NO 1: Perceptron Model

In [ ]:
from sklearn.datasets import load_digits

In [ ]:
digits = load_digits()
digits

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.],
        [ 0.,  0., 10., ..., 12.,  1.,  0.]]),
 'target': array([0, 1, 2, ..., 8, 9, 8]),
 'frame': None,
 'feature_names': ['pixel_0_0',
  'pixel_0_1',
  'pixel_0_2',
  'pixel_0_3',
  'pixel_0_4',
  'pixel_0_5',
  'pixel_0_6',
  'pixel_0_7',
  'pixel_1_0',
  'pixel_1_1',
  'pixel_1_2',
  'pixel_1_3',
  'pixel_1_4',
  'pixel_1_5',
  'pixel_1_6',
  'pixel_1_7',
  'pixel_2_0',
  'pixel_2_1',
  'pixel_2_2',
  'pixel_2_3',
  'pixel_2_4',
  'pixel_2_5',
  'pixel_2_6',
  'pixel_2_7',
  'pixel_3_0',
  'pixel_3_1',
  'pixel_3_2',
  'pixel_3_3',
  'pixel_3_4',
  'pixel_3_5',
  'pixel_3_6',
  'pixel_3_7',
  'pixel_4_0',
  'pixel_4_1',
  'pixel_4_2',
  'pixel_4_3',
  'pixel_4_4',
  'pixel_4_5',
  'pixel_4_6',
  'pixel_4_7',
  'pixel_5_0',
  'pixel_5_1',
 

In [ ]:
digits['data']

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [ ]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
from sklearn.linear_model import Perceptron

In [ ]:
# splitting the data

x = digits.data
y = digits.target

In [ ]:
pd.DataFrame(x).shape

(1797, 64)

In [ ]:
pd.DataFrame(y).value_counts()

0
3    183
1    182
5    182
4    181
6    181
9    180
7    179
0    178
2    177
8    174
Name: count, dtype: int64

In [ ]:
pd.DataFrame(y).nunique()

0    10
dtype: int64

In [ ]:
y

array([0, 1, 2, ..., 8, 9, 8])

In [ ]:
# training and testing the data
x_train, x_test, y_train, y_test  = train_test_split(x, y, test_size=0.2, random_state=42)

In [ ]:
# Building perceptron model
pp = Perceptron()
pp.fit(x_train, y_train)
print("What is the testing Accuracy")
print(pp.score(x_test,y_test))

What is the testing Accuracy
0.9527777777777777


In [ ]:
print("What is the training Accuracy")
print(pp.score(x_train ,y_train))

What is the training Accuracy
0.9714683368128044


In [ ]:
predicted = pp.predict(x_test)

In [ ]:
print('\n Confusion Matrix')
print(confusion_matrix(y_test, predicted))


 Confusion Matrix
[[32  0  0  0  1  0  0  0  0  0]
 [ 0 28  0  0  0  0  0  0  0  0]
 [ 0  0 33  0  0  0  0  0  0  0]
 [ 0  0  1 31  0  1  0  0  1  0]
 [ 0  0  0  0 46  0  0  0  0  0]
 [ 0  0  1  0  0 45  1  0  0  0]
 [ 0  0  0  0  0  1 34  0  0  0]
 [ 0  0  0  0  0  0  0 33  0  1]
 [ 0  2  0  0  2  1  0  0 25  0]
 [ 0  0  0  0  1  1  0  0  2 36]]


In [ ]:
print('\n Classification Report')
print(classification_report(y_test,predicted))


 Classification Report
              precision    recall  f1-score   support

           0       1.00      0.97      0.98        33
           1       0.93      1.00      0.97        28
           2       0.94      1.00      0.97        33
           3       1.00      0.91      0.95        34
           4       0.92      1.00      0.96        46
           5       0.92      0.96      0.94        47
           6       0.97      0.97      0.97        35
           7       1.00      0.97      0.99        34
           8       0.89      0.83      0.86        30
           9       0.97      0.90      0.94        40

    accuracy                           0.95       360
   macro avg       0.96      0.95      0.95       360
weighted avg       0.95      0.95      0.95       360



In [ ]:
## Case Number 2 : Multilayer Perceptrom Model - Regressing Problem



In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
tf.__version__

'2.19.0'

In [ ]:
dataset = pd.read_csv('HousingData.csv')
dataset.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622    3  222     18.7   

        B  LSTAT  MEDV  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90    NaN  36.2

In [ ]:
# checking for missing values
dataset.isnull().sum()

CRIM       20
ZN         20
INDUS      20
CHAS       20
NOX         0
RM          0
AGE        20
DIS         0
RAD         0
TAX         0
PTRATIO     0
B           0
LSTAT      20
MEDV        0
dtype: int64

In [ ]:
# Handling missing values by KNN imputation

from sklearn.impute import KNNImputer

In [ ]:
imputer = KNNImputer()
dataset1 = pd.DataFrame(imputer.fit_transform(dataset), columns = dataset.columns)

In [ ]:
dataset1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    float64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    float64
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  MEDV     506 non-null    float64
dtypes: float64(14)
memory usage: 55.5 KB


In [ ]:
# to check whether missing values are found
dataset1.isnull().sum()

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
MEDV       0
dtype: int64

In [ ]:
# feature Scaling
x = dataset1.iloc[:,:-1]
y = dataset1.iloc[:,-1]

In [ ]:
x

CRIM    ZN  INDUS  CHAS    NOX     RM    AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.20  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.90  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.10  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.80  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.20  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...    ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.10  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.70  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.00  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.30  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  78.86  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   7.56  
..       ...     ...    ...  
501     21.0  391.99   9.38  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 13 columns]

In [ ]:
y

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ... 
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: MEDV, Length: 506, dtype: float64

In [ ]:
# feature Scaling is mandatory step here

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaled_x = pd.DataFrame(scaler.fit_transform(x),columns = x.columns)
# same column names, should be scaled in tabular format so we are using dataframe
scaled_x

CRIM        ZN     INDUS      CHAS       NOX        RM       AGE  \
0   -0.425438  0.287980 -1.291623 -0.280228 -0.144217  0.413672 -0.125945   
1   -0.423028 -0.488492 -0.595127 -0.280228 -0.740262  0.194274  0.368604   
2   -0.423030 -0.488492 -0.595127 -0.280228 -0.740262  1.282714 -0.273949   
3   -0.422447 -0.488492 -1.310645 -0.280228 -0.835284  1.016303 -0.826256   
4   -0.418235 -0.488492 -1.310645 -0.280228 -0.835284  1.228577 -0.523029   
..        ...       ...       ...       ...       ...       ...       ...   
501 -0.418972 -0.488492  0.116000 -0.280228  0.158124  0.439316  0.014839   
502 -0.420966 -0.488492  0.116000 -0.280228  0.158124 -0.234548  0.289187   
503 -0.419187 -0.488492  0.116000 -0.280228  0.158124  0.984960  0.805396   
504 -0.413580 -0.488492  0.116000 -0.280228  0.158124  0.725672  0.744028   
505 -0.420720 -0.488492  0.116000 -0.280228  0.158124 -0.362767  0.367160   

          DIS       RAD       TAX   PTRATIO         B     LSTAT  
0    0.140214 -0.982843 -0.666608 -1.459000  0.441052 -1.085232  
1    0.557160 -0.867883 -0.987329 -0.303094  0.441052 -0.498835  
2    0.557160 -0.867883 -0.987329 -0.303094  0.396427 -1.219144  
3    1.077737 -0.752922 -1.106115  0.113032  0.416163 -1.372791  
4    1.077737 -0.752922 -1.106115  0.113032  0.441052 -0.721553  
..        ...       ...       ...       ...       ...       ...  
501 -0.625796 -0.982843 -0.803212  1.176466  0.387217 -0.465005  
502 -0.716639 -0.982843 -0.803212  1.176466  0.441052 -0.507293  
503 -0.773684 -0.982843 -0.803212  1.176466  0.441052 -0.992198  
504 -0.668437 -0.982843 -0.803212  1.176466  0.403225 -0.873791  
505 -0.613246 -0.982843 -0.803212  1.176466  0.441052 -0.676446  

[506 rows x 13 columns]

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(
                                      scaled_x, y , test_size = 0.2, random_state=42)

In [ ]:
## MultiLayer Perceptrom Model

In [ ]:
import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [ ]:
# Initialize the Sequential Model

model = Sequential()
# first  Fully connected Hidden layer
model.add(Dense(32,activation = 'relu', input_dim = 13))
# Second fully connected hidden layer
model.add(Dense(16,activation = 'relu'))
# output
model.add(Dense(1, activation = 'linear'))
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 32)             │           448 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 993 (3.88 KB)

 Trainable params: 993 (3.88 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
13*32+32

448

In [ ]:
32*16+16

528

In [ ]:
x_train.shape

(404, 13)

In [ ]:
404/32

12.625

In [ ]:
12*31

372

In [ ]:
model.compile(optimizer='adam', loss = 'mse') # since regression
history = model.fit(x_train,y_train, validation_data= (x_test,y_test),epochs=100, batch_size = 32)

Epoch 1/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 4s 121ms/step - loss: 629.1805 - val_loss: 543.1935
Epoch 2/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 624.7807 - val_loss: 525.9523
Epoch 3/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 586.3475 - val_loss: 510.9286
Epoch 4/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 569.8875 - val_loss: 496.1365
Epoch 5/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 519.6382 - val_loss: 479.1962
Epoch 6/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 586.7140 - val_loss: 457.9958
Epoch 7/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 528.2000 - val_loss: 431.8442
Epoch 8/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 491.4963 - val_loss: 400.0650
Epoch 9/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 479.3761 - val_loss: 362.4769
Epoch 10/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 433.6220 - val_loss: 320.2807
Epoch 11/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 399.8381 - val_loss: 274.1949
Epoch 12/100

In [ ]:
new_data = pd.read_csv('HousingData_test.csv')
new_data

CRIM  ZN  INDUS  CHAS  NOX  RM  AGE  DIS  RAD  TAX  PTRATIO    B  LSTAT  \
0  0.009  13      3     1  0.9   7   50  3.9    1  325       17  450      6   
1  0.090  14      5     0  0.8   8   65  6.0    2  400       16  430      7   
2  0.070  17      6     1  0.7   9   54  8.0    2  400       19  288      8   

   Unnamed: 13  
0          NaN  
1          NaN  
2          NaN

In [ ]:
new_data = new_data.iloc[:,:-1]
new_data

CRIM  ZN  INDUS  CHAS  NOX  RM  AGE  DIS  RAD  TAX  PTRATIO    B  LSTAT
0  0.009  13      3     1  0.9   7   50  3.9    1  325       17  450      6
1  0.090  14      5     0  0.8   8   65  6.0    2  400       16  430      7
2  0.070  17      6     1  0.7   9   54  8.0    2  400       19  288      8

In [ ]:
new_data.shape

(3, 13)

In [ ]:
scaled_new_data = pd.DataFrame(scaler.transform(new_data), columns = new_data.columns)
scaled_new_data

CRIM        ZN     INDUS      CHAS       NOX        RM       AGE  \
0 -0.425130  0.072293 -1.190660  3.702785  2.982858  1.019152 -0.674642   
1 -0.415830  0.115431 -0.898015 -0.280228  2.119025  2.443811 -0.133165   
2 -0.418126  0.244843 -0.751693  3.702785  1.255192  3.868469 -0.530248   

        DIS       RAD       TAX   PTRATIO         B     LSTAT  
0  0.049893 -0.982843 -0.494369 -0.672984  1.023259 -0.941452  
1  1.048169 -0.867883 -0.048923 -1.135347  0.803972 -0.800491  
2  1.998907 -0.867883 -0.048923  0.251741 -0.752967 -0.659530

In [ ]:
y_pred = model.predict(scaled_new_data)
print(y_pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 387ms/step
[[23.650484]
 [30.571552]
 [28.202797]]


In [ ]:
# RandomForest Regressor

from sklearn.ensemble import RandomForestRegressor


In [ ]:
rforest = RandomForestRegressor()
rforest.fit(x_train,y_train)

RandomForestRegressor()

In [ ]:
y_pred_test = rforest.predict(x_test)
y_pred_train = rforest.predict(x_train)
from sklearn import metrics
print(metrics.mean_squared_error(y_train,y_pred_train))
print(metrics.mean_squared_error(y_test,y_pred_test))

2.1319671509901
8.800264284313727


In [ ]:
new_data = rforest.predict(scaled_new_data)
new_data

array([28.508, 39.097, 35.254])

In [ ]:
y_pred

array([[23.650484],
       [30.571552],
       [28.202797]], dtype=float32)

In [ ]:
dataset1['MEDV'].describe()

count    506.000000
mean      22.532806
std        9.197104
min        5.000000
25%       17.025000
50%       21.200000
75%       25.000000
max       50.000000
Name: MEDV, dtype: float64

In [ ]:
# Linear Regression

from sklearn.linear_model import LinearRegression
linear = LinearRegression()
linear.fit(x_train, y_train)
y_pred_test_linear = linear.predict(x_test)
y_pred_train_linear = linear.predict(x_train)

from sklearn import metrics

print(metrics.mean_squared_error(y_train, y_pred_train_linear))
print(metrics.mean_squared_error(y_test, y_pred_test_linear))


21.751505399861465
24.407001654074588


In [ ]:
new_data_linear = linear.predict(scaled_new_data)
new_data_linear

array([27.39903948, 27.11481813, 28.47664213])

In [ ]:
print("Linear Result")
print(new_data_linear)
print("Random Forest Result")
print(new_data)
print("Multilayer Perceptron")
print(y_pred)


Linear Result
[27.39903948 27.11481813 28.47664213]
Random Forest Result
[28.508 39.097 35.254]
Multilayer Perceptron
[[23.650484]
 [30.571552]
 [28.202797]]


In [ ]:
history = model.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=500, batch_size=32)

Epoch 1/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 12.1274 - val_loss: 13.0472
Epoch 2/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 11.0099 - val_loss: 12.8909
Epoch 3/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 10.8136 - val_loss: 12.8996
Epoch 4/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 10.3131 - val_loss: 12.8553
Epoch 5/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 11.8272 - val_loss: 12.7260
Epoch 6/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 10.5482 - val_loss: 12.7148
Epoch 7/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.8134 - val_loss: 12.6895
Epoch 8/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.6656 - val_loss: 12.6136
Epoch 9/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.9767 - val_loss: 12.6496
Epoch 10/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 10.3315 - val_loss: 12.5436
Epoch 11/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.7286 - val_loss: 12.4968
Epoch 12/500
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7

In [ ]:
history = model.fit(x_train, y_train, epochs=10, batch_size=32)